using Firebase.Auth;
using Firebase.Database;
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.ResourceManagement.AsyncOperations;

public class GachaManager : MonoBehaviour
{
    [Header("UI")]
    [SerializeField] private SummonResultUI resultUI;

    #region FireBase Properties
    private string _uid;
    private DatabaseReference _dbRef;

    private float summonNormal;             // ë…¸ë§ ì†Œí™˜í™•ë¥            
    private float summonRare;               // ë ˆì–´ ì†Œí™˜í™•ë¥ 
    private float summonUnique;             // ìœ ë‹ˆíŠ¸ ì†Œí™˜í™•ë¥ 
    private float summonEpic;               // ì—í”½ ì†Œí™˜í™•ë¥ 
    private SummonLevel userSummonLevel;    // ì†Œí™˜ ë ˆë²¨
    private int userSummonCount;            // ìœ ì €ì˜ ì†Œí™˜ ë ˆë²¨ì—… ìˆ˜ì¹˜ 
    private int requireSummonCount;         // ì†Œí™˜ ë ˆë²¨ì—… ìš”êµ¬ëŸ‰
    #endregion

    // ê°€ì¤‘ì¹˜ í’€
    private Dictionary<string, float> GetWeightPool()
    {
        return new Dictionary<string, float>
        {
            { "Normal", summonNormal },
            { "Rare", summonRare },
            { "Unique", summonUnique },
            { "Epic", summonEpic }
        };
    }

    #region Unity LifeCycle

    private async void OnEnable()
    {
        _uid = CurrencyManager.Instance.UserID;
        _dbRef = CurrencyManager.Instance.DbRef;

        await LoadUserDataAsync();
        await LoadSummonConfigAsync();
    }
    private void OnDisable() { }
    #endregion

    #region Private

    //  ì†Œí™˜ ë ˆë²¨ ë³„ í™•ë¥ ì •ë³´ ë¡œë”©
    private async Task LoadSummonConfigAsync()
    {
        var snapshot = await _dbRef.Child("summon").Child(userSummonLevel.ToString()).GetValueAsync();

        summonNormal = Convert.ToSingle(snapshot.Child("normal").Value);
        summonRare = Convert.ToSingle(snapshot.Child("rare").Value);
        summonUnique = Convert.ToSingle(snapshot.Child("unique").Value);
        summonEpic = Convert.ToSingle(snapshot.Child("epic").Value);
        requireSummonCount = Convert.ToInt32(snapshot.Child("count").Value);
    }
    // ìœ ì € ë½‘ê¸°ì •ë³´ ë¡œë”©
    private async Task LoadUserDataAsync()
    {
        var snapProfile = await CurrencyManager.Instance.LoadUserProfileAsync();
        userSummonLevel = snapProfile.SummonLevel;
        userSummonCount = snapProfile.SummonCount;
    }
    private Task SaveUserSummonLevelAsync()
    {
        return _dbRef.Child("users").Child(_uid).Child("profile").Child("summonLevel").SetValueAsync((int)userSummonLevel);
    }

    private Task SaveUserSummonCountAsync()
    {
        return _dbRef.Child("users").Child(_uid).Child("profile").Child("summonCount").SetValueAsync(userSummonCount);
    }

    // ì¹´ë“œ ì •ë³´ í‘œê¸°
    private async Task<CardInfo> LoadCardInfoByRarity(string rarity)
    {
        string addressKey = rarity switch
        {
            "Normal" => "C001CardInfo",
            "Rare" => "C002CardInfo",
            "Unique" => "C003CardInfo",
            "Epic" => "C004CardInfo",
        };

        var handle = Addressables.LoadAssetAsync<CardInfo>(addressKey);

        await handle.Task;
        if (handle.Status == AsyncOperationStatus.Succeeded)
            return handle.Result;

        Debug.LogError($"[{nameof(LoadCardInfoByRarity)}] {addressKey} ë¡œë“œ ì‹¤íŒ¨");
        return null;
    }

    // ì‹¤ì œ ì†Œí™˜ ì½”ë“œ
    public async Task Summon(int times)
    {
        userSummonCount += times;
        if (userSummonCount >= requireSummonCount)
        {
            await LevelUpAsync();
        }

        var results = new List<CardInfo>();
        for (int i = 0; i < times; i++)
        {
            string rarityKey = DrawOne();
            CardInfo info = await LoadCardInfoByRarity(rarityKey);
            results.Add(info);
        }

        StartCoroutine(ProcessResultsCoroutine(results));
        await SaveUserSummonCountAsync();
        resultUI.ShowSummonResult(results);
        // await SaveGachaHistoryAsync(results); //ì†Œí™˜ê¸°ë¡ ì¶”ê°€
    }

    //  ì†Œí™˜ë ˆë²¨ ì—…
    private async Task LevelUpAsync()
    {
        // 1~9ê¹Œì§€ë§Œ ì²˜ë¦¬
        if (userSummonLevel < SummonLevel.level10)
        {
            userSummonLevel = (SummonLevel)((int)userSummonLevel + 1);
            userSummonCount = 0;

            await SaveUserSummonLevelAsync();
            await LoadSummonConfigAsync();
        }
    }

    //  ì†Œí™˜ í™•ë¥  ê²°ì •
    private string DrawOne()
    {
        var weightPool = GetWeightPool();
        float sum = weightPool.Values.Sum();
        float random = UnityEngine.Random.Range(0f, sum);

        foreach (var keyValue in weightPool)
        {
            if (random <= keyValue.Value) return keyValue.Key;
            random -= keyValue.Value;
        }
        return weightPool.Keys.Last();
    }

    //  ì†Œí™˜ê¸°ë¡ ì €ì¥í•˜ê¸°
    private async Task SaveGachaHistoryAsync(List<CardInfo> results)
    {
        var historyRef = _dbRef.Child("users").Child(_uid).Child("summonHistory");

        foreach (var card in results)
        {
            string key = historyRef.Push().Key;

            var data = new Dictionary<string, object>
        {
            { "timestamp", ServerValue.Timestamp },
            { "heroID", card.HeroID },

        };

            await historyRef.Child(key).SetValueAsync(data);
            // ê¸°ë¡ ì‚­ì œ
            // await historyRef.RemoveValueAsync();
        }
    }
    // ì˜ì›… ì¡°ê° ì •ë³´ë¥¼ ì—…ë¡œë“œí•˜ëŠ” ì½”ë£¨í‹´
    private IEnumerator ProcessResultsCoroutine(List<CardInfo> results)
    {
        // ğŸ†• HeroDataManagerì— ê²°ê³¼ ë°˜ì˜
        HeroDataManager.Instance.ApplyGachaResults(results);

        // ğŸ†• í•œë²ˆì— ì €ì¥
        HeroDataManager.Instance.SaveHeroDataToCache();
        HeroDataManager.Instance.SaveAllHeroDataToFirebase();

        yield return null;
        Debug.Log("ëª¨ë“  ê²°ê³¼ ì²˜ë¦¬ ì™„ë£Œ"); 
    }
    #endregion
}
/*
    TODO : ë½‘ê¸° í•´ì•¼í•  ì¼ ëª©ë¡
        ì˜ì›… ë½‘ê¸° í™•ë¥ , ë¦¬ìŠ¤íŠ¸ í’€ ìˆ˜ì •í•˜ê¸°
 */